dado = input(print("Digite algo: "))
print("O tipo desse dado é ", type(dado))
print("Tem espaços? ", dado.isspace())
print("É um numero? ", dado.isnumeric())
print("É alfabético", dado.isalpha())
print("É alfanumerico", dado.isalnum())
print("Está em maisculo? ", dado.isupper())
print("Está em minusculo? ", dado.islower())
print("Está capitalizada? ", dado.istitle())